### ISSUE TITLE
Lista de nomes actualizada

### ISSUE THREAD

**Issue by marado** [centraldedados/nomes_proprios#1]
Lista actualizada em 2015, em:

http://www.irn.mj.pt/sections/irn/a_registral/registos-centrais/docs-da-nacionalidade/vocabulos-admitidos-e/downloadFile/file/Lista_de_nomes30-09-2015.pdf?nocache=1444231503.53

**Comment by rlafuente** [comment]
Bom achado! Com o [Tabula](http://tabula.technology/) pode-se dar conta disto e atualizar a data package. Se não tiveres tempo, trato disso prá semana.

**Comment by rlafuente** [comment]
Os pormenores desta issue já estão a ser discutidas na #2, por isso fecho esta
