### ISSUE TITLE
Fonte "Público" actualizada

### ISSUE THREAD

**Issue by marado** [centraldedados/nomes_proprios#2]
Agora não me lembro no código, mas no site diz que há duas fontes, uma delas um PDF do Público com contagem de nomes.
O PDF do Público para 2015 já existe, e está em http://static.publico.pt/DOCS/Sociedade/Nomes%202015.pdf . Atenção que o PDF tem os nomes... "pouco normalizados".

**Comment by rlafuente** [comment]
Boa, obrigado! Já temos TPC para o encontro de sábado :-)

O que queres dizer com nomes pouco normalizados? Eu tinha dado uma vista de olhos e não encontrei nada de aparentemente errado...

**Comment by marado** [comment]
Ex.: existem 890 Salvador e 1 SALVADOR; André há muitos, mas Andre só um (e duvido que a falta de acento não seja um lapso)

**Comment by rlafuente** [comment]
Ok, neste encontro não tivemos tempo mas este issue será prático para quem quiser pegar na tarefa de integrar os dados de 2015.

Para os dados de 2014, usei o [Tabula](http://tabula.technology) para extrair a tabela do PDF e formatar o CSV final.

**Comment by marado** [comment]
Nota que o script (e resultado) do PR anterior só extrai os nomes do PDF, mas não o género - que, reparei entretanto - pode eventualmente ser útil. Se for o caso, pode-se melhorar o script (ou re-escrever isto com o Tabula).

**Comment by rlafuente** [comment]
Sim, é bastante importante guardar o género!

O Tabula corre-se manualmente, para apontar onde estão as tabelas, e ele cospe o CSV. Se não tiveres tempo, trato disto quando eu próprio tiver :-) Mas é uma ferramenta porreira que vale a pena experimentar, e este é um use case bastante simples!

**Comment by pires** [comment]
Usei o Google Sheets e um bocado de Apps Script para processar o ano de 2015, no entanto nao faco validacoes de acentos. Ou seja, `Joao == Joao (c/ tilde)` retorna `false`. Se nao houver problema com isto, terei todo o gosto em abrir PR com o CSV gerado.

**Comment by marado** [comment]
@pires Eu acho que isso é o importante, e que vale a pena fazer um PR. A questão dos acentos pode mesmo não ser consensual: Apesar de aparecer lá um Joao e um João, ou um André e um Andre, não sei se podemos ter a certeza que são o mesmo nome (typo) ou se são mesmo dois nomes diferentes...

**Comment by rlafuente** [comment]
Não entendi bem a questão da validação, mas venha o PR! Se houver alguma anomalia, resolvemos depois.
